### ISSUE TITLE
Add option to use SSH key instead of password

### ISSUE THREAD

**Issue by dzh01** [kd8bny/LiMEaide#36]
For acquiring memory dumps on AWS instance can you add an option to use ssh keys and not just passwords?

**Comment by kd8bny** [comment]
This should be pretty straight forward. Ill add it a feature for the next release.
[paramiko key bugs](https://github.com/paramiko/paramiko/issues/387)

**Comment by kd8bny** [comment]
This is all set in trunk. Will roll out in V2
